# Generated by Django 4.2.1 on 2023-05-15 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
